dist: trusty
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - p7zip-full

script:
- sudo bash ./create-image
- xz -z turingcoffee.img -c > turingcoffee.img.xz
