dist: trusty
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - p7zip-full
    - bsdtar

script:
  - wget "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_2.8+dfsg-6_amd64.deb"
  - ar p qemu-user-static_2.8+dfsg-6_amd64.deb data.tar.xz | bsdtar xf -
  - sudo cp -rf ./usr/* /usr/
  - sudo bash ./create-image

deploy:
  provider: releases
  skip_cleanup: true
  github_token: 5fbced7241746640f7cf52a395e25874fec01e1e
  file: DietPi_v150_RPi-armv6-(Jessie).img.xz
  on:
    branch: image
