dist: trusty
sudo: required
addons:
  apt:
    packages:
    - qemu
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - p7zip-full

script:
- wget "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_2.8+dfsg-6_amd64.deb"
- ar p qemu-user-static_2.8+dfsg-6_amd64.deb data.tar.xz | bsdtar xf - -C "/"
- sudo bash ./create-image
- xz -z turingcoffee.img -c > turingcoffee.img.xz
